### PR TITLE
Feature/multi targeting

### PR DESCRIPTION
**Pull request by enisn**
### Summary
This PR includes multi-targeting framework feature to support both `netcoreapp3.1` and `net5.0` at the same time.

### Instructions
If you have older version before pulling this PR; Remove all `bin` and `obj` folders in each project folder. Because they doesn't include `net5.0` folder and obj folder doesn't include `net5.0` nuget sources, it must be regenerated.

After that you can run 
```batch
dotnet pack -c RELEASE -o .packages
```
command and you'll see all packages are generated in `/.packages` folder 👍

---
This change is [Reviewable](https://reviewable.io/reviews/furkandeveloper/easyprofiler/67)

### CODE REVIEW

**Comment by furkandeveloper** [comment]
Best implementation. Thanks @enisn 🎉

**Review by furkandeveloper — COMMENTED** [review]
Reviewed

**Comment by furkandeveloper** [comment]
PR will be merge after analyzing problems that may occur with the current version. @enisn

**Comment by enisn** [comment]
Thank you @furkandeveloper

**Pull request merged**
