### PR TITLE
Sqlite support implementation

### PR DESCRIPTION
**Pull request by emrekara37**
## Sqlite support implementation

Hi @furkandeveloper ,
I added support SQLite.

Thanks for the useful package

---
This change is [Reviewable](https://reviewable.io/reviews/furkandeveloper/easyprofiler/69)

#55

### CODE REVIEW

**Review by enisn — APPROVED** [review]
LGTM

**Comment by enisn** [comment]
Also closes #55

**Comment by furkandeveloper** [comment]
Hi @emrekara37 👋

Firstly thank you for contribution on EasyProfiler. Currently have not problem but I will examine it a little more.

Happy Coding ! @emrekara37 ✨🎉

**Comment by furkandeveloper** [comment]
> LGTM

Thank you for review @enisn ✌

**Comment by furkandeveloper** [comment]
Hi @emrekara37, 
I am sorry for waited for this PR.
But `EasyProfiler` has been changed of architectural.

Therefore take a new fork and update the implementation for the PR below.

EasyProfiler waiting for new feature.
Happy Coding ✨🎉✌
fyi @enisn

**Comment by enisn** [comment]
If there is a branch that is able to merge this PR, I can work on it. 
Because Architectural changes are major and might have breaking changes.

---

I think @emrekara37 can solve conflict and re-open PR. SQLite implementation won't be affected much.

**Pull request closed without merging**
